name: Deploy OWFINANCE dentro de public_html

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # ajusta si tu proyecto requiere otra
          extensions: mbstring, intl, pdo_mysql, bcmath, gd, zip, curl, xml
          coverage: none

      - name: Copiar .env.example local (solo para build)
        run: cp .env.example .env

      - name: Instalar dependencias (Composer en CI)
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # Si compilas assets con Vite, descomenta:
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Build assets
      #   run: |
      #     npm ci
      #     npm run build

      - name: Preparar bundle a subir
        run: |
          mkdir -p __upload__
          rsync -a --delete \
            --exclude ".git" --exclude ".github" \
            --exclude "__upload__" \
            --exclude "node_modules" \
            ./ __upload__/

      - name: Iniciar SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Añadir known_hosts
        run: ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Chequear permisos y directorios
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "echo 'Directorio actual:'; pwd; 
             echo 'Usuario actual:'; whoami;
             echo 'Verificando directorios disponibles:'; 
             ls -la .; 
             echo 'Verificando estructura de owfinance:';
             if [ -d './owfinance' ]; then ls -la ./owfinance; fi;
             echo 'Verificando directorio public_html:';
             if [ -L 'public_html' ]; then 
               echo 'public_html es un symlink que apunta a:'; 
               readlink -f public_html;
             elif [ -d 'public_html' ]; then
               echo 'public_html es un directorio normal';
             else
               echo 'public_html no existe';
             fi"

      - name: Crear carpeta app_upload en directorio owfinance
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "mkdir -p './owfinance/app_upload' || echo 'No se pudo crear el directorio, usando directorio temporal';
             if [ ! -d './owfinance/app_upload' ]; then mkdir -p '/tmp/app_upload'; fi"

      - name: Subir bundle a app_upload
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "if [ -d './owfinance/app_upload' ]; then 
               echo 'Usando owfinance/app_upload'; 
               TARGET_DIR='./owfinance/app_upload'; 
             else 
               echo 'Usando directorio temporal'; 
               TARGET_DIR='/tmp/app_upload'; 
             fi; 
             echo \"TARGET_DIR=$TARGET_DIR\" > /tmp/target_dir.txt"
          
          TARGET_DIR=$(ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cat /tmp/target_dir.txt | grep TARGET_DIR | cut -d'=' -f2")
          echo "Uploading to: $TARGET_DIR"
          
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./__upload__/ \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$TARGET_DIR/"

      - name: Instalar/actualizar app en public_html
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "PHP_CLI='php' bash -s" <<'REMOTE'
          set -euo pipefail

          # Establecer rutas según la estructura del servidor
          SITE_ROOT=$(pwd)
          PHP_CLI="${PHP_CLI:-php}"
          
          # Detectar ubicación del directorio app_upload
          if [ -d "./owfinance/app_upload" ]; then
            UPLOAD_DIR="$SITE_ROOT/owfinance/app_upload"
            echo "Usando directorio de carga: $UPLOAD_DIR"
          elif [ -d "/tmp/app_upload" ]; then
            UPLOAD_DIR="/tmp/app_upload"
            echo "Usando directorio temporal: $UPLOAD_DIR"
          else
            echo "ERROR: No se encuentra directorio de carga"
            exit 1
          fi
          
          # Establecer directorio de la aplicación
          APP_DIR="$SITE_ROOT/owfinance/current"
          PUBLIC_DIR="$APP_DIR/public"
          
          echo "Directorio de aplicación: $APP_DIR"
          echo "Directorio público: $PUBLIC_DIR"

          # 1) Crear estructura de directorios si no existe
          mkdir -p "$SITE_ROOT/owfinance/releases"
          mkdir -p "$SITE_ROOT/owfinance/shared"
          
          # 2) Preservar .env si ya existe
          if [ -f "$APP_DIR/.env" ]; then
            mkdir -p "$SITE_ROOT/owfinance/shared"
            cp "$APP_DIR/.env" "$SITE_ROOT/owfinance/shared/.env"
          fi
          
          # 3) Crear nuevo release
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RELEASE_DIR="$SITE_ROOT/owfinance/releases/$TIMESTAMP"
          
          echo "Creando nuevo release en: $RELEASE_DIR"
          mkdir -p "$RELEASE_DIR"
          
          # 4) Mover archivos del upload al release
          echo "Copiando archivos de $UPLOAD_DIR a $RELEASE_DIR"
          rsync -a --delete "$UPLOAD_DIR/" "$RELEASE_DIR/"
          
          # 5) Configurar .env desde shared si existe
          if [ -f "$SITE_ROOT/owfinance/shared/.env" ]; then
            echo "Usando .env compartido"
            cp "$SITE_ROOT/owfinance/shared/.env" "$RELEASE_DIR/.env"
          fi
          
          # 6) Establecer permisos
          mkdir -p "$RELEASE_DIR/storage" "$RELEASE_DIR/bootstrap/cache"
          chmod -R ug+rwX "$RELEASE_DIR/storage" "$RELEASE_DIR/bootstrap/cache" || true
          
          # 7) Ejecutar comandos de Laravel
          cd "$RELEASE_DIR"
          $PHP_CLI artisan key:generate --force || true
          $PHP_CLI artisan config:cache
          $PHP_CLI artisan route:cache || true
          $PHP_CLI artisan view:cache || true
          
          # 8) Migrar base de datos
          echo "Ejecutando migraciones..."
          $PHP_CLI artisan migrate --force || echo "Error en migraciones, continuando..."
          
          # 9) Crear symlinks para storage
          rm -rf "$RELEASE_DIR/public/storage" || true
          if [ ! -d "$SITE_ROOT/owfinance/shared/storage" ]; then
            mkdir -p "$SITE_ROOT/owfinance/shared/storage/app/public"
            cp -a "$RELEASE_DIR/storage/." "$SITE_ROOT/owfinance/shared/storage/"
          fi
          
          rm -rf "$RELEASE_DIR/storage"
          ln -sfn "$SITE_ROOT/owfinance/shared/storage" "$RELEASE_DIR/storage"
          
          ln -sfn "$RELEASE_DIR/storage/app/public" "$RELEASE_DIR/public/storage" || {
            echo "Symlink denegado; copiando storage público…"
            mkdir -p "$RELEASE_DIR/public/storage"
            rsync -a "$SITE_ROOT/owfinance/shared/storage/app/public/" "$RELEASE_DIR/public/storage/"
          }
          
          # 10) Proteger de acceso web
          cat > "$RELEASE_DIR/.htaccess" <<'HTX'
          <IfModule mod_authz_core.c>
            Require all denied
          </IfModule>
          <IfModule !mod_authz_core.c>
            Deny from all
          </IfModule>
          HTX
          
          # 11) Actualizar enlace current a nuevo release
          if [ -d "$APP_DIR" ] && [ ! -L "$APP_DIR" ]; then
            # Si current es un directorio y no un symlink, moverlo a backup
            mv "$APP_DIR" "$APP_DIR.bak"
          elif [ -L "$APP_DIR" ]; then
            # Si es un symlink, eliminarlo
            rm "$APP_DIR"
          fi
          
          # Crear symlink del nuevo release
          ln -sfn "$RELEASE_DIR" "$APP_DIR"
          
          # 12) Actualizar symlink de public_html si no existe
          if [ ! -L "$SITE_ROOT/public_html" ] || [ ! -e "$SITE_ROOT/public_html" ]; then
            echo "Creando symlink public_html -> $PUBLIC_DIR"
            ln -sfn "$PUBLIC_DIR" "$SITE_ROOT/public_html"
          fi
          
          # 13) Limpieza: mantener solo los 3 releases más recientes
          cd "$SITE_ROOT/owfinance/releases"
          ls -t | tail -n +4 | xargs -r rm -rf
          
          echo "Deploy completado exitosamente en $RELEASE_DIR"
          REMOTE

      - name: Verificar archivos publicados
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "echo 'Estructura final:';
             echo '- Directorio actual:'; pwd;
             echo '- Directorio owfinance:'; ls -la ./owfinance;
             echo '- Releases:'; ls -la ./owfinance/releases;
             echo '- Current symlink apunta a:'; readlink -f ./owfinance/current;
             echo '- Public_html symlink apunta a:'; readlink -f ./public_html;
             echo '- Contenido de public_html:'; ls -la ./public_html | head -n 20;"
